### ISSUE TITLE
Migrate away from PHP_Crypt

### ISSUE THREAD

**Issue by paragonie-scott** [NextPass/NextPass#5]

**Comment by nexttrex** [comment]
Hey, thanks for the warning. Luckily I am already using defuse/php-encryption for the actual Password encryption. I will remove phpcrypt as fast as possible and warn even more to not use NextPass yet.

**Comment by larthoman** [comment]
Before you consider switching do realize that there is evidence to suggest that paragonie-scott is being quite melodramatic:

https://www.reddit.com/r/PHP/comments/41dnct/full_disclosure_it_essentially_wins_crypto/cz1j3iy

PHP-Crypt is not inherently insecure as paragonie-scott would have you believe. It can be used in an insecure manner but that doesn't mean it is insecure. Cryptography is a tool that needs to be used correctly and in conjunction with other tools. Some of the defaults PHP-Crypt uses are ill advised but those defaults can be changed (and indeed you may very well have changed them - I do not know).

To be perfectly blunt, if there's a problem with the crypto in NextPass, it's not because the author of PHP-Crypt doesn't know what they're doing - it's that you don't know what you're doing, and switching to some other library may not change that.

To use an analogy..  if all you want out of a car is to have a smooth ride, get an automatic transmission. If you want to control torque independent of acceleration, get a manual transmission.

There are crypto libraries out there that take care of all the little details for you. And there are those that don't. PHP-Crypt is of the latter. That doesn't mean it's bad - it just means that it may not be be the right tool for everyone.

**Comment by paragonie-scott** [comment]
> PHP-Crypt is not inherently insecure as paragonie-scott would have you believe.

32 bits of entropy in the key generation, the use of **extremely** insecure defaults, etc. [See also](https://cr.yp.to/talks/2015.01.07/slides-djb-20150107-a4.pdf).

But hey, if @larthoman is the expert here, listen to him. I'm out.

**Comment by nexttrex** [comment]
Like it says the Readme of NextPass: Nobody is suppose to use NextPass for real passwords, yet. 

I just recently uploaded this project to github, so of course there are vulnerabilities. Truth be told: I just used phpcrypt to have it working without worrying to much about encryption right at the beginning. I wanted to replace this libary from the beginning on.

Even if phpcrypt is might be secure, I will replace it anyways. It is just too small and therefore not very well tested.
